### ISSUE TITLE
Reuse variable statements for other method calls

### ISSUE THREAD

**Issue by mitchellolsthoorn** [syntest-framework/syntest-core#249]
Currently, we make new variable statements for each method call we make. It would be good to check the existing variables already created and re-use them if the type matches

**Comment by dstallenberg** [comment]
This is a language specific feature as the relevant code for this feature is in the syntest-javascript and syntest-solidity repositories.

There already is an issue for this in the syntest-javascript repository.
https://github.com/syntest-framework/syntest-javascript/issues/9
